run-name: build android and web
on:
  push:
    branches:
      - main
env:
  # Define your Expo CLI version
  EXPO_CLI_VERSION: "0.18.29"
  UBUNTU: ubuntu-22.04
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

jobs:
  checkout_job:
    runs-on: ubuntu-22.04
    steps:
      # This step checks out a copy of your repository.
      - name: check out repository
        uses: actions/checkout@v4
  test_secret_job:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ secrets.TEST_SECRET }}

  setup-pkg-job:
    runs-on: ubuntu-22.04
    steps:
      - run: npm install -g expo-cli@$EXPO_CLI_VERSION
      - run: npm ci
      # should not modify package-lock
      - run: npx expo install
  prepare-scripts-job:
    runs-on: ubuntu-22.04
    steps:
      - run: apt-get install jq
